name: Upload to Confluence from TXT

on:
  push:
    paths:
      - "*.txt" # Detecta cualquier archivo .txt en el repositorio
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  process-txt-to-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Print Environment Variables (Masked)
        run: |
          echo "Checking environment variables (masked):"
          echo "CONFLUENCE_BASE_URL: ${CONFLUENCE_BASE_URL:0:4}****${CONFLUENCE_BASE_URL: -4}"
          echo "CONFLUENCE_USERNAME: ${CONFLUENCE_USERNAME:0:4}****${CONFLUENCE_USERNAME: -4}"
          echo "SPACE_KEY: ${SPACE_KEY:0:4}****${SPACE_KEY: -4}"
          echo "CONFLUENCE_API_TOKEN: ****" # No mostramos nada del token por seguridad
        env:
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          SPACE_KEY: ${{ secrets.SPACE_KEY }}

      - name: Verify Required Secrets
        run: |
          missing_secrets=()
          [ -z "$CONFLUENCE_BASE_URL" ] && missing_secrets+=("CONFLUENCE_BASE_URL")
          [ -z "$CONFLUENCE_USERNAME" ] && missing_secrets+=("CONFLUENCE_USERNAME")
          [ -z "$CONFLUENCE_API_TOKEN" ] && missing_secrets+=("CONFLUENCE_API_TOKEN")
          [ -z "$SPACE_KEY" ] && missing_secrets+=("SPACE_KEY")
          
          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "Error: Missing required secrets: ${missing_secrets[*]}"
            exit 1
          fi
          echo "All required secrets are set"
        env:
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          SPACE_KEY: ${{ secrets.SPACE_KEY }}

      - name: Process TXT and Upload to Confluence
        env:
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          SPACE_KEY: ${{ secrets.SPACE_KEY }}
        run: |
          python process_txt_to_confluence.py
        continue-on-error: false # El workflow fallará si hay error en el script

      - name: Upload Process Log
        if: always() # Ejecutar incluso si los pasos anteriores fallan
        uses: actions/upload-artifact@v3
        with:
          name: process-log
          path: |
            *.log
            *.txt
          retention-days: 5
