name: Upload to Confluence from TXT

on:
  push:
    paths:
      - "*.txt" # Detecta cualquier archivo .txt en el repositorio

jobs:
  process-txt-to-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Process TXT and Upload to Confluence
        env:
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          SPACE_KEY: ${{ secrets.SPACE_KEY }}
        run: |
          python process_txt_to_confluence.py
